---
- name: copy artifact
  hosts: tomcat
  become: yes

  tasks:
    - name: copy artifcat
      copy:
        src: /mnt/artefact/
        dest: /mnt/artefact/
        owner: root
        group: root
        mode: 0755
